Sentiment Analysis Using DistilBert pretrained model and fine tuning it with the amazon dataset


# Read data from the file


In [ ]:
import json

In [ ]:
reviews = []
for line in open('Office_Products_5.json', 'r'):
	reviews.append(json.loads(line))

In [ ]:
print(len(reviews))

53258


In [ ]:
print((reviews[0]))

{'reviewerID': 'A32T2H8150OJLU', 'asin': 'B00000JBLH', 'reviewerName': 'ARH', 'helpful': [3, 4], 'reviewText': "I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling.  I searched for another one to replace it, but found one difficult to come by in my area.  So, I decided to buy up and purchased an HP 49G.  What a mistake!  I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best.  The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you.  It's programmable.  It does basic statistics well, and many business applications too.  The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend.  I didn't even

In [ ]:
	review_text=[]
	review_star=[]

In [ ]:
for l in range(0,len(reviews)):
		review_text.append(reviews[l]['reviewText'])
		review_star.append(reviews[l]['overall'])

In [ ]:
print(review_text[0:5])

["I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling.  I searched for another one to replace it, but found one difficult to come by in my area.  So, I decided to buy up and purchased an HP 49G.  What a mistake!  I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best.  The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you.  It's programmable.  It does basic statistics well, and many business applications too.  The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend.  I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!", 'WHY THIS BELATED REVIE

In [ ]:
print(review_star[0:15])

[5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0]


In [ ]:
review_set=[]
review_star_set=[]
c1=c2=c3=c4=c5=0
for l in range(0,len(reviews)):
	if(reviews[l]['overall']==5 and c5<2000):
		review_set.append(reviews[l]['reviewText'])
		review_star_set.append(reviews[l]['overall'])
		c5=c5+1
	if(reviews[l]['overall']==4 and c4<2000):
		review_set.append(reviews[l]['reviewText'])
		review_star_set.append(reviews[l]['overall'])
		c4=c4+1
	if(reviews[l]['overall']==3 and c3<1000):
		review_set.append(reviews[l]['reviewText'])
		review_star_set.append(reviews[l]['overall'])
		c3=c3+1
	if(reviews[l]['overall']==2 and c2<2000):
		review_set.append(reviews[l]['reviewText'])
		review_star_set.append(reviews[l]['overall'])
		c2=c2+1
	if(reviews[l]['overall']==1 and c1<2000):
		review_set.append(reviews[l]['reviewText'])
		review_star_set.append(reviews[l]['overall'])
		c1=c1+1

In [ ]:
print('1 star:',c1)
print('2 star:',c2)
print('3 star:',c3)
print('4 star:',c4)
print('5 star:',c5)
print("total reviews:",(c1+c2+c3+c4+c5))

1 star: 1130
2 star: 1726
3 star: 1000
4 star: 2000
5 star: 2000
total reviews: 7856


In [ ]:
review_sentiment=[]
	#len(review_sentiment)
p=0
for l in range(0,len(review_star_set)):
	if review_star_set[l]==4.0 or review_star_set[l]==5.0:
		p=1
	elif (review_star_set[l]==3.0):
		p=1
	elif(review_star_set[l]==1.0 or review_star_set[l]==2.0):
		p=0
	review_sentiment.append(p)

In [ ]:
len(review_set)

7856

In [ ]:
len(review_sentiment)

7856

##Preprocessing Steps

In [ ]:
import pandas as pd

In [ ]:
review_df=pd.DataFrame(review_set)

In [ ]:
review_df[0][0]

"Not much to write about here, but it does exactly what it's supposed to. filters out the pop sounds. now my recordings are much more crisp. it is one of the lowest prices pop filters on amazon so might as well buy it, they honestly work the same despite their pricing,"

In [ ]:
import string

In [ ]:
def remove_punctuation(text):
  punc_free=''.join([i for i in text if i not in string.punctuation])
  return punc_free

review_df['clean']=review_df[0].apply(lambda x: remove_punctuation(x))
review_df.head()


0                                              clean
0  I bought my first HP12C in about 1984 or so, a...  I bought my first HP12C in about 1984 or so an...
1  WHY THIS BELATED REVIEW? I feel very obliged t...  WHY THIS BELATED REVIEW I feel very obliged to...
2  I have an HP 48GX that has been kicking for mo...  I have an HP 48GX that has been kicking for mo...
3  I've started doing more finance stuff recently...  Ive started doing more finance stuff recently ...
4  For simple calculations and discounted cash fl...  For simple calculations and discounted cash fl...

In [ ]:
review_df['clean']=review_df['clean'].apply(lambda x: x.lower())

In [ ]:
review_set=list(review_df['clean'])

not much to write about here but it does exactly what its supposed to filters out the pop sounds now my recordings are much more crisp it is one of the lowest prices pop filters on amazon so might as well buy it they honestly work the same despite their pricing


In [ ]:
review_sentiment.count(0)

2856

In [ ]:
review_sentiment.count(1)

5000

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(review_set, review_sentiment, test_size=0.20, random_state=0)

In [ ]:
print(X_test)

["These labels are of good quality and just what they should be. They print smoothly without jamming up my printer, they provide good coverage for covering up old addresses or other unwanted info and most importantly they STICK! I hate cheap labels that require you to tape the edges down so they don't peel off.", "I love Paper Mate products and almost exclusively use their pens.  I was very excited to hear about the Inkjoy line (the name alone made me smile!).  Unfortunately the 300RT pens have been a major disappointment.  First the good: (1) the colored inks are quite nice and (2) um...that's about it.  The problem is that pens have had serious problems with smudging and leaking.  Almost half of the pens from my 8-pack almost immediately started leaking so severely that it's difficult for the pen to retract.  To use these pens, I have to clean the nib, which is covered in goo, and then I still have issues with smudging (I eventually threw away the offenders).  The pens are also not v

In [ ]:
!pip install transformers

     |████████████████████████████████| 3.1 MB 5.3 MB/s 
     |████████████████████████████████| 56 kB 4.3 MB/s 
     |████████████████████████████████| 895 kB 46.8 MB/s 
     |████████████████████████████████| 3.3 MB 37.2 MB/s 
     |████████████████████████████████| 596 kB 37.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from transformers import DistilBertTokenizerFast

In [ ]:
tokenizer=DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

In [ ]:
train_encodings=tokenizer(X_train, truncation=True, padding=True)
test_encodings=tokenizer(X_test, truncation=True, padding=True)

In [ ]:
import tensorflow as tf

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings),y_train))

In [ ]:
test_dataset=tf.data.Dataset.from_tensor_slices((dict(test_encodings),y_test))

In [ ]:
from transformers import TFDistilBertForSequenceClassification, TFTrainer, TFTrainingArguments

In [ ]:
training_args = TFTrainingArguments(
    output_dir='./results',
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    eval_steps=10,
    warmup_steps=20,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
)

In [ ]:
with training_args.strategy.scope():
  model = TFDistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertForSequenceClassification: ['vocab_projector', 'vocab_layer_norm', 'vocab_transform', 'activation_13']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier', 'pre_classifier', 'dropout_59']
You should probably TRAIN this model on a down-stream task to be able to use i

In [ ]:
trainer=TFTrainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset
)

/usr/local/lib/python3.7/dist-packages/transformers/trainer_tf.py:114: FutureWarning: The class `TFTrainer` is deprecated and will be removed in version 5 of Transformers. We recommend using native Keras instead, by calling methods like `fit()` and `predict()` directly on the model object. Detailed examples of the Keras style can be found in our examples at https://github.com/huggingface/transformers/tree/master/examples/tensorflow
  FutureWarning,


In [ ]:
trainer

In [ ]:
trainer.train()

In [ ]:
train_output=trainer.predict(train_dataset)

In [ ]:
print(train_output)

PredictionOutput(predictions=array([[-0.7987517 ,  0.6486858 ],
       [ 0.3896119 , -0.3722451 ],
       [ 0.3097744 , -0.28352737],
       ...,
       [-0.7126323 ,  0.57664883],
       [-0.58957887,  0.48825747],
       [-2.3112588 ,  1.9224186 ]], dtype=float32), label_ids=array([1, 0, 0, ..., 1, 1, 1], dtype=int32), metrics={'eval_loss': 0.3479639106731075})


In [ ]:
import numpy as np

In [ ]:
train_prediction=np.argmax(train_output[0], axis = - 1)

In [ ]:
print(train_prediction)

[1 0 0 ... 1 1 1]


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
train_cm=confusion_matrix(y_train,train_prediction)

In [ ]:
print(train_cm)

[[1696  568]
 [ 378 3642]]


In [ ]:
train_accuracy=accuracy_score(y_train,train_prediction)

In [ ]:
print(train_accuracy)

0.8494589433481858


In [ ]:
train_report=classification_report(y_train, train_prediction)
print(train_report)

              precision    recall  f1-score   support

           0       0.82      0.75      0.78      2264
           1       0.87      0.91      0.89      4020

    accuracy                           0.85      6284
   macro avg       0.84      0.83      0.83      6284
weighted avg       0.85      0.85      0.85      6284



In [ ]:
trainer.evaluate(test_dataset)

{'eval_loss': 0.4014852119214607}

In [ ]:
test_output=trainer.predict(test_dataset)

In [ ]:
print(test_output)

PredictionOutput(predictions=array([[-2.2466846 ,  1.886569  ],
       [ 0.59529525, -0.56147826],
       [ 0.3277425 , -0.30125624],
       ...,
       [-0.57291704,  0.483345  ],
       [-0.46874532,  0.42241153],
       [-0.23653363,  0.2245677 ]], dtype=float32), label_ids=array([1, 0, 0, ..., 1, 0, 0], dtype=int32), metrics={'eval_loss': 0.40351378315626973})


In [ ]:
test_prediction=np.argmax(test_output[0], axis = - 1)

In [ ]:
test_cm=confusion_matrix(y_test, test_prediction)

In [ ]:
print(test_cm)

[[411 181]
 [104 876]]


In [ ]:
test_acc=accuracy_score(y_test,test_prediction)

In [ ]:
print(test_acc)

0.8187022900763359


In [ ]:
test_report=classification_report(y_test, test_prediction)
print(test_report)

              precision    recall  f1-score   support

           0       0.80      0.69      0.74       592
           1       0.83      0.89      0.86       980

    accuracy                           0.82      1572
   macro avg       0.81      0.79      0.80      1572
weighted avg       0.82      0.82      0.82      1572



In [ ]:
import numpy as np


In [ ]:
trainer.save_model('sentiment_model')